### ISSUE TITLE
(intern) Trimming within a percentage of the best weight

### ISSUE THREAD

**Issue by matsen** [matsengrp/historydag#15]
Let's say that our objective isn't to just trim to the best tree but to trim such that all trees have weight within some percentage of the best one. Is trimming in this setting a well-defined operation? Like, can we translate this per-tree criterion to a per-edge one?
Does the answer change if we have a lovely weighting function for the edges of the hDAG (imagine, for example, a mutability parsimony)?

I think the answer is strictly no, this isn't well-defined. Consider for example a DAG expressing a set of histories T, in which there are histories with weight 10, 11, 12. We know we can trim to only express the histories with weight 10, but it's quite possible that the DAG constructed from only the histories in T with weight 11 necessarily also expresses histories with weight 10 and 12. Then any DAG containing all the histories in T with weight 10 and 11 also must contain some histories with weight 12.
However, if we 'trim' as much as possible while still containing all histories with weights 10 and 11 (which is the same as just constructing a DAG from all such histories), the resulting object could be of interest somehow, despite still containing histories of higher weight.
We could also construct something like the "largest subset of the DAG that only contains histories with weights 11 and 12".

**Comment by willdumm** [comment]
![image](https://user-images.githubusercontent.com/27025156/167224452-a8f9fe0c-15ac-447f-b131-dc6d582499b2.png)

As an illustration of the two possible paths that can be taken for this problem, if the black blob is a history DAG, with trees arranged vertically by weight, and the red line is the weight threshold we'd like to trim to, we can look for:
* The green blob, which is the "smallest trim containing all trees with less than the threshold weight". This thing exists and is unique, because it's just the DAG union of all trees in the original DAG with less than the threshold weight. An algorithm to find this thing efficiently could be useful, though (without having to enumerate all trees with less than the threshold weight)
* The blue blob, which is the "largest trim containing only trees with less than the threshold weight". This thing may not be unique, but a non-trivial trim containing only trees with less than the threshold weight certainly exists -- it's the one containing only minimum weight trees.

**Comment by willdumm** [comment]
This is closed by PR #33
